name: "build project"
# Whenever a push run the job
on: 
  push:

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.1
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_export_templates.tpz
        relative_project_path: ./
        export_debug: false
        archive_output: true
        cache: true
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
    - name: upload artifact
      id: upload_artifact
      uses: actions/upload-artifact@v3
      with:
        name: builds 
        path: ${{ steps.export.outputs.archive_directory }}/*
        if-no-files-found: error
